all:
  vars:
    ansible_user: ivkochkozharov
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    jobmanager:
      hosts:
        lang33.delta.sbrf.ru:

    taskmanagers:
      hosts:
        lang33.delta.sbrf.ru:
        lang34.delta.sbrf.ru:
        lang35.delta.sbrf.ru:
        lang36.delta.sbrf.ru:
        lang37.delta.sbrf.ru:

    flink_cluster:
      children:
        jobmanager:
        taskmanagers:
